version: "3"

### Install task in linux:
# sudo apt -y install bash-completion; sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/bin; eval "$(~/bin/task --completion bash)"

### Install task in mac:
# brew install go-task
# eval "$(task --completion zsh)"

includes:
  work:
    taskfile: Taskfile_local.yml
    optional: true
    flatten: true

tasks:
  default: task -l

  direnv:add:uv:
    desc: "Add layout uv to the .envrc file"
    cmds:
      - echo "layout uv" >> .envrc
      - direnv allow .
    dir: "{{.USER_WORKING_DIR}}"

  direnv:add:poetry:
    desc: "Add layout poetry to the .envrc file"
    cmds:
      - echo "layout poetry" >> .envrc
      - direnv allow .
    dir: "{{.USER_WORKING_DIR}}"

  uv:init:
    desc: "Initialize uv with envrc"
    cmds:
      - uv init
      - task: direnv:add:uv
    dir: "{{ .USER_WORKING_DIR }}"

  bw:search:
    desc: "Search Bitwarden vault"
    cmds:
      - bw list items --search {{.CLI_ARGS}}

  bw:sync:
    desc: "Sync Bitwarden vault"
    cmds:
      - bw sync
