abbr --add DOCKER 'cd /var/lib/docker'
abbr --add Dps 'docker ps'
abbr --add Dpshort 'docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"'
abbr --add Dpsa 'docker ps -a'
abbr --add Dpsl 'docker ps -l'
abbr --add Dins 'docker inspect'
abbr --add Drm 'docker rm -v'
abbr --add Drma 'docker rm -v (docker ps -a -q)'
abbr --add Drml 'docker rm -v (docker ps -l -q)'
abbr --add Drmi 'docker rmi'
abbr --add Drmv 'docker volume rm'
abbr --add Dimg 'docker images'
abbr --add Dimga 'docker images -a'
abbr --add Dip 'docker ps -q | xargs -n 1 docker inspect --format "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} {{ .Name }}" | sed "s/ \// /"'
abbr --add Dstart 'docker start'
abbr --add Dstop 'docker stop'
abbr --add Dstopall 'docker stop (docker ps -aq)'
abbr --add Dprune 'docker image prune'

abbr --add qls 'virsh list --all'
abbr --add qstart 'virsh start'
abbr --add qstop 'virsh destroy'
