# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
		export TERM=xterm
fi
# Alias definitions.
if [ -f ~/.shell_aliases ]; then
    . ~/.shell_aliases
fi
if [ -f ~/.work_aliases ]; then
    . ~/.work_aliases
fi
if [ -f ~/.root_aliases ]; then
    . ~/.root_aliases
fi

PS1="\\[\\e[1;31m\\]\\u\\[\\e[1;37m\\]@\\[\\e[1;36m\\]\\h:\\[\\e[1;33m\\] \\w\\[\\e[1;36m\\] \\$\\[\\e[0m\\] "
